### ISSUE TITLE
脚本报错，几乎是每个脚本跑到最后都报这个，大佬看下

### ISSUE THREAD

**Issue by pizixi** [ClassmateLin/scripts#24]
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000201F9029A60>
Traceback (most recent call last):
  File "C:\Python\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
Exception ignored in: Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001C486F19A60>Exception ignored in: Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001E56D6B9A60>Exception ignored in:     Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001A039839A60>
<function _ProactorBasePipeTransport.__del__ at 0x00000241804C9A60>Exception ignored in:
<function _ProactorBasePipeTransport.__del__ at 0x000001CF2E2E9A60>self.close()<function _ProactorBasePipeTransport.__del__ at 0x000001AAB34F9A60>
Traceback (most recent call last):

<function _ProactorBasePipeTransport.__del__ at 0x000002508C659A60>Traceback (most recent call last):

Traceback (most recent call last):
  File "C:\Python\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
Traceback (most recent call last):

  File "C:\Python\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
Traceback (most recent call last):
  File "C:\Python\Python38\lib\asyncio\proactor_events.py", line 108, in close
Traceback (most recent call last):
  File "C:\Python\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Python\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
Traceback (most recent call last):
      File "C:\Python\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Python\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
                  File "C:\Python\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
self.close()        self.close()self._loop.call_soon(self._call_connection_lost, None)self.close()self.close()
self.close()self.close()

self.close()  File "C:\Python\Python38\lib\asyncio\proactor_events.py", line 108, in close

  File "C:\Python\Python38\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Python\Python38\lib\asyncio\base_events.py", line 719, in call_soon
  File "C:\Python\Python38\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Python\Python38\lib\asyncio\proactor_events.py", line 108, in close

      File "C:\Python\Python38\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Python\Python38\lib\asyncio\proactor_events.py", line 108, in close
            self._check_closed()  File "C:\Python\Python38\lib\asyncio\proactor_events.py", line 108, in close
self._loop.call_soon(self._call_connection_lost, None)        self._loop.call_soon(self._call_connection_lost, None)    self._loop.call_soon(self._call_connection_lost, None)

self._loop.call_soon(self._call_connection_lost, None)self._loop.call_soon(self._call_connection_lost, None)

  File "C:\Python\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
self._loop.call_soon(self._call_connection_lost, None)  File "C:\Python\Python38\lib\asyncio\base_events.py", line 719, in call_soon

self._loop.call_soon(self._call_connection_lost, None)  File "C:\Python\Python38\lib\asyncio\base_events.py", line 719, in call_soon
  File "C:\Python\Python38\lib\asyncio\base_events.py", line 719, in call_soon
  File "C:\Python\Python38\lib\asyncio\base_events.py", line 719, in call_soon

      File "C:\Python\Python38\lib\asyncio\base_events.py", line 719, in call_soon

          File "C:\Python\Python38\lib\asyncio\base_events.py", line 719, in call_soon
    raise RuntimeError('Event loop is closed')self._check_closed()
  File "C:\Python\Python38\lib\asyncio\base_events.py", line 719, in call_soon
self._check_closed()self._check_closed()    self._check_closed()
RuntimeError        self._check_closed()
self._check_closed()
  File "C:\Python\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
:
self._check_closed()
  File "C:\Python\Python38\lib\asyncio\base_events.py", line 508, in _check_closed

  File "C:\Python\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
Event loop is closed  File "C:\Python\Python38\lib\asyncio\base_events.py", line 508, in _check_closed

  File "C:\Python\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
      File "C:\Python\Python38\lib\asyncio\base_events.py", line 508, in _check_closed

        raise RuntimeError('Event loop is closed')  File "C:\Python\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')    raise RuntimeError('Event loop is closed')raise RuntimeError('Event loop is closed')
    raise RuntimeError('Event loop is closed')

RuntimeErrorraise RuntimeError('Event loop is closed')raise RuntimeError('Event loop is closed')RuntimeErrorRuntimeErrorRuntimeErrorRuntimeError:

: : : : Event loop is closedRuntimeErrorRuntimeErrorEvent loop is closedEvent loop is closedEvent loop is closedEvent loop is closed
: :

Event loop is closedEvent loop is closedException ignored in:

<function _ProactorBasePipeTransport.__del__ at 0x000001AAB34F9A60>
Traceback (most recent call last):
  File "C:\Python\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Python\Python38\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Python\Python38\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "C:\Python\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by ClassmateLin** [comment]
Python only switched the default event loop to proactor from 3.8 onwards. https://docs.python.org/3/library/asyncio-policy.html#asyncio.DefaultEventLoopPolicy

**Comment by ClassmateLin** [comment]
换到3.7试试
