### ISSUE TITLE
from config import JD_DEBUG

### ISSUE THREAD

**Issue by VectorZhao** [ClassmateLin/scripts#3]
日志-jd_burning_summer.py
## 更新任务状态成功
Traceback (most recent call last):
  File "raw_jd_burning_summer.py", line 14, in <module>
    from utils.console import println
  File "/ql/scripts/utils/console.py", line 8, in <module>
    from config import JD_DEBUG
ImportError: cannot import name 'JD_DEBUG' from 'config' (/usr/lib/python3.8/site-packages/config/__init__.py)
## 更新任务状态成功

config里面没有JD_DEBUG

**Comment by h605290713** [comment]
[root@localhost jd_scripts]# python3.7 jd_burning_summer.py 
Traceback (most recent call last):
  File "jd_burning_summer.py", line 14, in <module>
    from utils.console import println
  File "/root/jd_scripts/utils/console.py", line 8, in <module>
    from config import JD_DEBUG
  File "/root/jd_scripts/config.py", line 44, in <module>
    with open(CONF_PATH, 'r', encoding='utf-8-sig') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/root/jd_scripts/conf/config.yaml'

**Comment by VectorZhao** [comment]
> [root@localhost jd_scripts]# python3.7 jd_burning_summer.py
> Traceback (most recent call last):
> File "jd_burning_summer.py", line 14, in
> from utils.console import println
> File "/root/jd_scripts/utils/console.py", line 8, in
> from config import JD_DEBUG
> File "/root/jd_scripts/config.py", line 44, in
> with open(CONF_PATH, 'r', encoding='utf-8-sig') as f:
> FileNotFoundError: [Errno 2] No such file or directory: '/root/jd_scripts/conf/config.yaml'

估计需要配置作者给的docker才可以使用。config.yaml。是配置文件吧

**Comment by h605290713** [comment]
这个需要调用chrome 浏览器 图形界面的

**Comment by ClassmateLin** [comment]
需要配合容器食用
